export interface ScentSnapshot {
  id: string;
  title: string;
  tags: string[];
  notes: string;
  timestamp: string;
  location: string;
  lat: number;
  lng: number;
  intensity: number;
  radius: number;
  duration: number;
  colorSeed: number;
}

export const mockSnapshots: ScentSnapshot[] = [
  {
    id: '1',
    title: 'Pearl River Delta Mist',
    tags: ['jasmine', 'lotus', 'humid air'],
    notes: 'Morning over the estuary. Floral and thick — the air pressed against skin like warm silk.',
    timestamp: '2026-02-14T08:15:00',
    location: 'Guangdong, China',
    lat: 23.1,
    lng: 113.3,
    intensity: 82,
    radius: 68,
    duration: 9,
    colorSeed: 1,
  },
  {
    id: '2',
    title: 'Golden Gate Fog',
    tags: ['salt', 'eucalyptus', 'cool mist'],
    notes: 'The fog rolled through at dusk. Everything disappeared. Only the smell remained — oceanic, clean, immense.',
    timestamp: '2026-03-04T18:30:00',
    location: 'San Francisco, CA',
    lat: 37.7749,
    lng: -122.4194,
    intensity: 76,
    radius: 64,
    duration: 11,
    colorSeed: 2,
  },
  {
    id: '3',
    title: 'Monterey Bay at Low Tide',
    tags: ['kelp', 'brine', 'sea grass'],
    notes: 'The bay exposed its floor. Dense, iodine-rich, alive. A smell ancient enough to belong to the sea itself.',
    timestamp: '2026-03-01T09:20:00',
    location: 'Monterey, CA',
    lat: 36.6002,
    lng: -121.8947,
    intensity: 88,
    radius: 72,
    duration: 8,
    colorSeed: 0,
  },
  {
    id: '4',
    title: 'Paris, After Rain',
    tags: ['stone', 'petrichor', 'café'],
    notes: 'Cobblestones still steaming. The smell of warm bread through an open door. Paris after rain is a different city.',
    timestamp: '2026-02-22T11:45:00',
    location: 'Paris, France',
    lat: 48.8566,
    lng: 2.3522,
    intensity: 79,
    radius: 60,
    duration: 13,
    colorSeed: 3,
  },
  {
    id: '5',
    title: 'Kyoto Temple Grove',
    tags: ['cedar', 'incense', 'moss'],
    notes: 'Ancient cedar and old incense. The silence between trees had its own weight — woody, humid, sacred.',
    timestamp: '2026-01-18T07:30:00',
    location: 'Kyoto, Japan',
    lat: 35.0116,
    lng: 135.7681,
    intensity: 71,
    radius: 55,
    duration: 14,
    colorSeed: 4,
  },
  {
    id: '6',
    title: 'Marrakech Spice Souk',
    tags: ['cumin', 'saffron', 'rose'],
    notes: 'Spice dust caught the low afternoon light. Rose water and dry heat. Every breath felt like a map of the world.',
    timestamp: '2026-01-31T15:10:00',
    location: 'Marrakech, Morocco',
    lat: 31.6295,
    lng: -7.9811,
    intensity: 93,
    radius: 58,
    duration: 7,
    colorSeed: 3,
  },
  {
    id: '7',
    title: 'Oslo Fjord at Dusk',
    tags: ['pine', 'cold water', 'granite'],
    notes: 'Still air, cold water surface. Pine resin carried from the ridge. The fjord smelled of compressed time.',
    timestamp: '2026-02-05T19:55:00',
    location: 'Oslo, Norway',
    lat: 59.9139,
    lng: 10.7522,
    intensity: 68,
    radius: 74,
    duration: 16,
    colorSeed: 4,
  },
  {
    id: '8',
    title: 'Havana Afternoon',
    tags: ['tobacco', 'bougainvillea', 'salt'],
    notes: 'Slow heat, open windows, salt from the Malecón. The city exuded something warm and slightly combustible.',
    timestamp: '2026-02-10T14:20:00',
    location: 'Havana, Cuba',
    lat: 23.1136,
    lng: -82.3666,
    intensity: 84,
    radius: 62,
    duration: 10,
    colorSeed: 5,
  },
  {
    id: '9',
    title: 'Ligurian Coastal Path',
    tags: ['thyme', 'sea spray', 'wild herb'],
    notes: 'Dry herbs crushed underfoot. The sea below, the sun above. An Italian afternoon distilled into scent.',
    timestamp: '2026-02-17T12:00:00',
    location: 'Cinque Terre, Italy',
    lat: 44.1,
    lng: 9.73,
    intensity: 77,
    radius: 66,
    duration: 12,
    colorSeed: 6,
  },
  {
    id: '10',
    title: 'Kerala Backwater Dawn',
    tags: ['coconut', 'water lily', 'clay'],
    notes: 'Canoe through still water at first light. Coconut palms, damp clay, and blooming water lilies.',
    timestamp: '2026-01-25T06:10:00',
    location: 'Kerala, India',
    lat: 9.4981,
    lng: 76.3388,
    intensity: 86,
    radius: 70,
    duration: 9,
    colorSeed: 1,
  },
  {
    id: '11',
    title: 'Vancouver Island Rain',
    tags: ['fir', 'soil', 'rain'],
    notes: 'Temperate rainforest after a heavy fall. Fir and hemlock and the sweetness of saturated soil.',
    timestamp: '2026-03-01T10:40:00',
    location: 'Vancouver Island, CA',
    lat: 49.6,
    lng: -125.45,
    intensity: 74,
    radius: 78,
    duration: 15,
    colorSeed: 2,
  },
  {
    id: '12',
    title: 'Saharan Sunrise',
    tags: ['dry sand', 'iron', 'warmth'],
    notes: 'The desert at first light — cold air warming fast, iron-rich earth releasing the night\'s cold. Something primal.',
    timestamp: '2026-01-12T06:50:00',
    location: 'Merzouga, Morocco',
    lat: 31.08,
    lng: -4.01,
    intensity: 65,
    radius: 80,
    duration: 18,
    colorSeed: 0,
  },
];

export const mockContacts = [
  { id: 'c1', name: 'Ariel Tan', initials: 'AT' },
  { id: 'c2', name: 'Marcus Webb', initials: 'MW' },
  { id: 'c3', name: 'Soo-Jin Park', initials: 'SJ' },
  { id: 'c4', name: 'Lena Vogt', initials: 'LV' },
  { id: 'c5', name: 'Idris Eloma', initials: 'IE' },
  { id: 'c6', name: 'Nina Roth', initials: 'NR' },
];